name: $(Date:yyyyMMdd)$(Rev:.r)

# variables: 

stages: 
- stage: build
  displayName: build
  pool: kubernetescluster
  jobs:
  - job: TestJob
    steps: 
    - bash: kubectl get pods --all-namespaces
