name: $(Date:yyyyMMdd)$(Rev:.r)

pool: kubernetescluster 

jobs:
- job: CreateDevelopmentNamespace
  displayName: Create development namespace
  steps:
  - bash: kubectl create -f ./namespaces/namespace-development.yaml
    workingDirectory: ./src/K8s
