apiVersion: apps/v1
kind: Deployment
metadata:
<<<<<<< HEAD
  name: bikemanagement.api
  namespace: development
=======
  name: bikemanagement-api
>>>>>>> 3a401bdedcb0eab4a619d2a120dc1b04519d3288
spec:
  selector:
    matchLabels:
      app: bikemanagement-api
  template:
    metadata:
      labels:
        app: bikemanagement-api
    spec:
      containers:
      - name: bikemanagement-api
        image: ghcr.io/tom171296/bikemanagement-api:latest
        imagePullPolicy: Always
        resources:
          limits:
            memory: "128Mi"
            cpu: "500m"
        ports:
        - containerPort: 80
      
      imagePullSecrets:
        - name: regcred
