apiVersion: apps/v1
kind: Deployment
metadata:
  name: bikemanagement.api
  namespace: development
spec:
  replicas: 2
  selector:
    matchLabels:
      app: bikemanagement-api
  template:
    metadata:
      labels:
        app: bikemanagement-api
    spec:
      containers:
      - name: bikemanagement-api
        image: ghcr.io/tom171296/bikemanagement-api:latest
        imagePullPolicy: Always
        resources:
          limits:
            memory: "128Mi"
            cpu: "500m"
        ports:
        - containerPort: 80
      
      imagePullSecrets:
        - name: regcred

---

apiVersion: v1
kind: Service
metadata:
  name: bikemanagement-api
  namespace: development
spec:
  selector:
    app: bikemanagement-api
  ports:
  - port: 12345
    targetPort: 80