apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: minimal-ingress
  namespace: development
  labels:
      name: minimal-ingress
  annotations:
    kubernetes.io/ingress.class: istio
spec:
  rules:
  - http:
      paths:
      - pathType: Prefix
        path: "/bikemanagement"
        backend:
          service:
            name: bikemanagement-api
            port:
              number: 12345
