name: BikeManagement-API

on:
  workflow_dispatch:

jobs:
  push_to_registry:
    name: Push Docker image to GitHub Packages
    runs-on: ubuntu-latest
    steps:
      - name: Check out the repo
        uses: actions/checkout@v2
        
      - name: Login to GitHub Container Registry
        uses: docker/login-action@v1
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.CR_PAT }}

      - name: Push to GitHub Packages
        uses: docker/build-push-action@v2
        with:
          context: ./src/BikeManagement/BikeManagement.API/
          push: true
          tags: ghcr.io/tom171296/bikemanagement-api:latest
    
  release_to_cluster:
      name: release to kubernetes cluster
      runs-on: [self-hosted, kubernetescluster]
      steps:
        - name: basic deployment
          uses: Azure/k8s-deploy@v1.3
          with:
            namespace: 'development'
            manifests: |
                ./src/K8s/deployments/deployment-bikemanagement-api.yaml
          