name: BikeManagement-API

on:
  workflow_dispatch:

jobs:

  build_push_image:

    name: Push Docker image to GitHub Packages
    runs-on: ubuntu-latest

    steps:
      - name: Check out the repo
        uses: actions/checkout@v2
        
      - name: Login to GitHub Container Registry
        uses: docker/login-action@v1
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.CR_PAT }}

      - name: Push to GitHub Packages
        uses: docker/build-push-action@v2
        with:
          context: ./src/BikeManagement/BikeManagement.API/
          push: true
          tags: ghcr.io/tom171296/bikemanagement-api:latest
    
  developement_deployment:
  
      needs: [build_push_image]
      name: release to kubernetes cluster
      environment:
        name: Development
      env:
        namespace_name: development
      runs-on: [self-hosted, kubernetescluster]
      
      steps:
        - name: Check out the repo
          uses: actions/checkout@v2
          
        - name: deploy bikemanagement-api to dev
          run: sudo kubectl apply -f ./deployment-bikemanagement-api.yaml
          working-directory: ./src/K8s/deployments/
          
