# This is a basic workflow to help you get started with Actions

name: Setup cluster 

# Controls when the action will run. 
on: 
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  setup-namespaces:
    # The type of runner that the job will run on
    runs-on: [self-hosted, kubernetescluster]

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2

      # - name: create development namespace
      #   run: kubectl create -f ./namespaces/namespace-development.json
      #   working-directory: ./src/K8s

      # - name: create secret
      #   run: kubectl -n=development create secret docker-registry regcred --docker-server=<your-registry-server> --docker-username=<your-name> --docker-password=<your-pword> --docker-email=<your-email>

      - name: Create istio operator namespace
        run: kubectl create -f ./namespaces/namespace-istio-system.json
        working-directory: ./src/K8s

      - name: apply istio operator
        run: kubectl apply -f ./operators/operator-istio.yaml
        working-directory: ./src/K8s

      - name: apply ingress
        run: kubectl apply -f ./networking/minimal-ingress.yaml
        working-directory: ./src/K8s

        


        